spring:
  application:
    name: spring-base

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbase?serverTimezone=Asia/Seoul
    username: root
    password: test12
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    root: INFO
    com:
      springbase: DEBUG
