global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]
  #추가
  - job_name: "springbase"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
